const express = require("express");
const router = express.Router();
const Carwash = require("../../Controllers/Carwash/Carwash.controller");
const { authenticateJWT } = require("../../Controllers/User.controller");
router.post("/order", Carwash.addOrderToShop);
router.get("/getall", Carwash.getAllOrdersForShop);             
router.get("/getindividual", Carwash.getShopById);
router.patch("/order/status", Carwash.changeOrderStatus);
router.post("/addreview/:shopId", Carwash.postReviewToShop);
router.post("/postorders/:shopId", Carwash.placeOrderToShop);
router.patch("/updateshop", Carwash.updateShop);
module.exports = router;
